In [180]:
import matplotlib

In [181]:
import numpy as np

In [182]:
from random import *

In [183]:
#Dans la zone étudiée, on estime qu'il y a 4 fois plus de gazelles que de lions/lionnes
#Ainsi, par exemple, sur une zone matrice de 25 "cases" on comptera 12 gazelles, 3 lions/lionnes et donc 10 cases vides
#La gazelle prend comme valeur 1
#La meute de lionne prend la valeur 2
#Le lion prend la valeur 3
#Une case vide prend la valeur 0

In [299]:
#Création d'une matrice d composée uniquement de 0 représentant une case vide
#matrice composée de a lignes et b colonnes (a et b étant des valeurs que l'on peut modifier directement dans le programme)
a=10
b=10
d = np.zeros((a,b))
d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [300]:
#Création d'une liste M avec toutes les positions possibles de la matrice d 
M=[]
for k in range (0,a) : 
    for i in range (0,b) : 
        M.append([k,i])

In [301]:
M

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [0, 8],
 [0, 9],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [1, 5],
 [1, 6],
 [1, 7],
 [1, 8],
 [1, 9],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [2, 5],
 [2, 6],
 [2, 7],
 [2, 8],
 [2, 9],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3],
 [3, 4],
 [3, 5],
 [3, 6],
 [3, 7],
 [3, 8],
 [3, 9],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [4, 8],
 [4, 9],
 [5, 0],
 [5, 1],
 [5, 2],
 [5, 3],
 [5, 4],
 [5, 5],
 [5, 6],
 [5, 7],
 [5, 8],
 [5, 9],
 [6, 0],
 [6, 1],
 [6, 2],
 [6, 3],
 [6, 4],
 [6, 5],
 [6, 6],
 [6, 7],
 [6, 8],
 [6, 9],
 [7, 0],
 [7, 1],
 [7, 2],
 [7, 3],
 [7, 4],
 [7, 5],
 [7, 6],
 [7, 7],
 [7, 8],
 [7, 9],
 [8, 0],
 [8, 1],
 [8, 2],
 [8, 3],
 [8, 4],
 [8, 5],
 [8, 6],
 [8, 7],
 [8, 8],
 [8, 9],
 [9, 0],
 [9, 1],
 [9, 2],
 [9, 3],
 [9, 4],
 [9, 5],
 [9, 6],
 [9, 7],
 [9, 8],
 [9, 9]]

In [302]:
indices = np.random.choice(np.arange(len(M)), a*b, replace=False)


In [303]:
#Création d'un tableau "positions" représentant toutes les positions de la matrice "d" dans le désordre 
positions = np.array(M)[indices]

In [304]:
positions

array([[4, 8],
       [4, 4],
       [9, 7],
       [7, 1],
       [7, 5],
       [0, 3],
       [6, 4],
       [1, 7],
       [2, 5],
       [4, 2],
       [2, 6],
       [6, 7],
       [5, 4],
       [3, 3],
       [9, 9],
       [6, 8],
       [9, 5],
       [6, 3],
       [3, 9],
       [9, 8],
       [0, 4],
       [6, 5],
       [3, 6],
       [5, 6],
       [8, 7],
       [2, 2],
       [0, 7],
       [2, 8],
       [3, 7],
       [1, 4],
       [4, 3],
       [6, 0],
       [5, 7],
       [7, 7],
       [1, 2],
       [7, 6],
       [4, 9],
       [9, 3],
       [8, 1],
       [1, 3],
       [7, 3],
       [6, 6],
       [7, 2],
       [8, 3],
       [3, 4],
       [6, 1],
       [4, 5],
       [4, 0],
       [4, 1],
       [8, 4],
       [1, 6],
       [5, 1],
       [2, 3],
       [0, 8],
       [8, 0],
       [3, 1],
       [9, 6],
       [3, 2],
       [5, 8],
       [0, 2],
       [8, 2],
       [8, 5],
       [6, 2],
       [5, 3],
       [2, 7],
       [0, 1],
       [2,

In [305]:
#On remplace maintenant dans la matrice d, certaines cases vides par une case représentant une gazelle dont la valeur est
#égale à 1. On estime qu'il faut remplir la matrice à 48% de gazelles
n = len(positions)
c=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==1 : 
        c=c+1
q=0
while c<0.48*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==1 : 
        q=q+1
    else : 
        d[position[0],position[1]] = 1
        print("En {} on a mis une gazelle".format(position))
        c = c+1
        q=q+1

[4 8]
[4 4]
[9 7]
[7 1]
[7 5]
[0 3]
[6 4]
[1 7]
[2 5]
[4 2]
[2 6]
[6 7]
[5 4]
[3 3]
[9 9]
[6 8]
[9 5]
[6 3]
[3 9]
[9 8]
[0 4]
[6 5]
[3 6]
[5 6]
[8 7]
[2 2]
[0 7]
[2 8]
[3 7]
[1 4]
[4 3]
[6 0]
[5 7]
[7 7]
[1 2]
[7 6]
[4 9]
[9 3]
[8 1]
[1 3]
[7 3]
[6 6]
[7 2]
[8 3]
[3 4]
[6 1]
[4 5]
[4 0]
[4 1]
[8 4]
[1 6]
[5 1]
[2 3]
[0 8]
[8 0]
[3 1]
[9 6]
[3 2]
[5 8]
[0 2]
[8 2]
[8 5]
[6 2]
[5 3]
[2 7]
[0 1]
[2 0]
[6 9]
[1 9]
[0 5]
[4 6]
[0 0]
[5 0]
[8 9]
[5 2]
[2 1]
[8 8]
[3 8]
[7 4]
[7 9]
[0 9]
[1 8]
[1 0]
[4 7]
[5 9]
[9 2]
[7 8]
[9 1]
[9 4]
[0 6]
[3 0]
[8 6]
[1 1]
[7 0]
[5 5]
[1 5]
[2 9]
[2 4]
[3 5]
[9 0]
En [4 8] on a mis une gazelle
En [4 4] on a mis une gazelle
En [9 7] on a mis une gazelle
En [7 1] on a mis une gazelle
En [7 5] on a mis une gazelle
En [0 3] on a mis une gazelle
En [6 4] on a mis une gazelle
En [1 7] on a mis une gazelle
En [2 5] on a mis une gazelle
En [4 2] on a mis une gazelle
En [2 6] on a mis une gazelle
En [6 7] on a mis une gazelle
En [5 4] on a mis une gazelle
En [3 3] o

In [306]:
#On remplace maintenant quelques cases vide par une case représenant les lions. 
#On estime qu'ils sont présents à 4%
n = len(positions)
x=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==2 : 
        x=x+1
q=0
while x<0.04*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==2 : 
        q=q+1
    elif value == 1 :
        q=q+1
    else : 
        d[position[0],position[1]] = 2
        print("En {} on a mis un lion".format(position))
        x = x+1
        q=q+1

[4 8]
[4 4]
[9 7]
[7 1]
[7 5]
[0 3]
[6 4]
[1 7]
[2 5]
[4 2]
[2 6]
[6 7]
[5 4]
[3 3]
[9 9]
[6 8]
[9 5]
[6 3]
[3 9]
[9 8]
[0 4]
[6 5]
[3 6]
[5 6]
[8 7]
[2 2]
[0 7]
[2 8]
[3 7]
[1 4]
[4 3]
[6 0]
[5 7]
[7 7]
[1 2]
[7 6]
[4 9]
[9 3]
[8 1]
[1 3]
[7 3]
[6 6]
[7 2]
[8 3]
[3 4]
[6 1]
[4 5]
[4 0]
[4 1]
[8 4]
[1 6]
[5 1]
[2 3]
[0 8]
[8 0]
[3 1]
[9 6]
[3 2]
[5 8]
[0 2]
[8 2]
[8 5]
[6 2]
[5 3]
[2 7]
[0 1]
[2 0]
[6 9]
[1 9]
[0 5]
[4 6]
[0 0]
[5 0]
[8 9]
[5 2]
[2 1]
[8 8]
[3 8]
[7 4]
[7 9]
[0 9]
[1 8]
[1 0]
[4 7]
[5 9]
[9 2]
[7 8]
[9 1]
[9 4]
[0 6]
[3 0]
[8 6]
[1 1]
[7 0]
[5 5]
[1 5]
[2 9]
[2 4]
[3 5]
[9 0]
En [4 1] on a mis un lion
En [8 4] on a mis un lion
En [1 6] on a mis un lion
En [5 1] on a mis un lion


In [307]:
#On rajoute maintenant les meutes de lionnes éstimées à 8%
n = len(positions)
y=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==3 : 
        y=y+1
q=0
while y<0.08*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value == 3 : 
        q=q+1
    elif value == 1 :
        q=q+1
    elif value == 2 :
        q=q+1
    else : 
        d[position[0],position[1]] = 3
        print("En {} on a mis une lionne".format(position))
        y = y+1
        q=q+1

En [2 3] on a mis une lionne
En [0 8] on a mis une lionne
En [8 0] on a mis une lionne
En [3 1] on a mis une lionne
En [9 6] on a mis une lionne
En [3 2] on a mis une lionne
En [5 8] on a mis une lionne
En [0 2] on a mis une lionne


In [308]:
#On affiche maintenant la matrice d avec toute la population placée aléatoirement. 
d

array([[ 0.,  0.,  3.,  1.,  1.,  0.,  0.,  1.,  3.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  2.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  3.,  0.,  1.,  1.,  0.,  1.,  0.],
       [ 0.,  3.,  3.,  1.,  1.,  0.,  1.,  1.,  0.,  1.],
       [ 1.,  2.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 0.,  2.,  0.,  0.,  1.,  0.,  1.,  1.,  3.,  0.],
       [ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 3.,  1.,  0.,  1.,  2.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1.,  3.,  1.,  1.,  1.]])

In [309]:
d.size

100

In [310]:
len(np.where(d == 1.)[0])

48

In [311]:
len(np.where(d == 2.)[0])

4

In [312]:
len(np.where(d == 3.)[0])

8

In [313]:
#On s'interesse aux voisins de chaque case
def voisins(x,y) : 
    """Renvoie les voisins de (x,y) dans la matrice d en faisant attention aux coins/bords"""
    L = []

    #coin supérieur gauche
    if x == 0 and y == 0 : 
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
    
    #coin supérieur droit
    elif x == 0 and y == (b-1) : 
        L.append(d[(x+1),y])
        L.append(d[x,(y-1)])
    
    #coin inférieur gauche
    elif x == (a-1) and y == 0 : 
        L.append(d[x,(y+1)])
        L.append(d[(x-1),y])
    
    #coin inférieur droit
    elif x == (a-1) and y == (b-1) : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
    
    #ligne du haut
    elif x == 0 and y != 0:
        L.append(d[(x,(y-1))])
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
        
    #ligne de gauche
    elif x !=0 and y == 0 : 
        L.append(d[(x-1),y])
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
        
    #ligne du bas
    elif x == (a-1) and y != 0 : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
        L.append(d[x,(y+1)])
    
    #ligne de droite
    elif x != 0 and y == (b-1) : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
        L.append(d[(x+1),y])

    #cas général
    else :
        L.append(d[x,(y-1)])
        L.append(d[(x-1),y])
        L.append(d[x,(y+1)])
        L.append(d[(x+1),y])

    return L
    

In [321]:
voisins(9,0)

[0.0, 3.0]

In [322]:
L = voisins(x,y)

In [323]:
#On s'interrese maintenant aux interractions entre les gazelles et les lions/meutes de lionnes
#Pour l'instant on se met dans le cas ou dès lors qu'il y a rencontre entre gazelle et lion/meute de lionne, 
#la gazelle se fait attraper et elle fait donc place à une nouvelle case vide dont la valeur est 0

In [326]:
N = choice(L)
N

1.0

In [297]:
a

[0.0, 3.0]

In [298]:
b

10