In [1]:
import matplotlib

In [2]:
import numpy as np

In [3]:
#Dans la zone étudiée, on estime qu'il y a 4 fois plus de gazelles que de lions/lionnes
#Ainsi, par exemple, sur une zone matrice de 25 "cases" on comptera 12 gazelles, 3 lions/lionnes et donc 10 cases vides
#La gazelle prend comme valeur 1
#La meute de lionne prend la valeur 2
#Le lion prend la valeur 3
#Une case vide prend la valeur 0

In [78]:
#Création d'une matrice d composée uniquement de 0 représentant une case vide
#matrice composée de a lignes et b colonnes (a et b étant des valeurs que l'on peut modifier directement dans le programme)
a=10
b=10
d = np.zeros((a,b))
d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [79]:
#Création d'une liste L avec toutes les positions possibles de la matrice d 
L=[]
for k in range (0,a) : 
    for i in range (0,b) : 
        L.append([k,i])

In [80]:
L

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [0, 8],
 [0, 9],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [1, 5],
 [1, 6],
 [1, 7],
 [1, 8],
 [1, 9],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [2, 5],
 [2, 6],
 [2, 7],
 [2, 8],
 [2, 9],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3],
 [3, 4],
 [3, 5],
 [3, 6],
 [3, 7],
 [3, 8],
 [3, 9],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [4, 8],
 [4, 9],
 [5, 0],
 [5, 1],
 [5, 2],
 [5, 3],
 [5, 4],
 [5, 5],
 [5, 6],
 [5, 7],
 [5, 8],
 [5, 9],
 [6, 0],
 [6, 1],
 [6, 2],
 [6, 3],
 [6, 4],
 [6, 5],
 [6, 6],
 [6, 7],
 [6, 8],
 [6, 9],
 [7, 0],
 [7, 1],
 [7, 2],
 [7, 3],
 [7, 4],
 [7, 5],
 [7, 6],
 [7, 7],
 [7, 8],
 [7, 9],
 [8, 0],
 [8, 1],
 [8, 2],
 [8, 3],
 [8, 4],
 [8, 5],
 [8, 6],
 [8, 7],
 [8, 8],
 [8, 9],
 [9, 0],
 [9, 1],
 [9, 2],
 [9, 3],
 [9, 4],
 [9, 5],
 [9, 6],
 [9, 7],
 [9, 8],
 [9, 9]]

In [81]:
indices = np.random.choice(np.arange(len(L)), a*b, replace=False)


In [82]:
#Création d'un tableau "positions" représentant toutes les positions de la matrice "d" dans le désordre 
positions = np.array(L)[indices]

In [83]:
positions

array([[0, 1],
       [8, 4],
       [4, 5],
       [7, 2],
       [9, 7],
       [1, 1],
       [1, 3],
       [8, 9],
       [8, 5],
       [7, 3],
       [0, 6],
       [8, 8],
       [9, 8],
       [4, 7],
       [6, 5],
       [0, 4],
       [3, 6],
       [3, 4],
       [5, 3],
       [7, 6],
       [1, 5],
       [2, 6],
       [6, 7],
       [7, 4],
       [8, 2],
       [3, 0],
       [6, 3],
       [0, 0],
       [2, 9],
       [3, 8],
       [3, 1],
       [7, 0],
       [9, 2],
       [2, 8],
       [2, 0],
       [9, 3],
       [5, 6],
       [0, 3],
       [9, 5],
       [0, 5],
       [6, 6],
       [1, 9],
       [5, 7],
       [4, 0],
       [2, 4],
       [9, 9],
       [2, 5],
       [4, 2],
       [6, 1],
       [3, 3],
       [9, 0],
       [9, 4],
       [5, 1],
       [4, 6],
       [5, 9],
       [8, 3],
       [5, 5],
       [0, 9],
       [3, 9],
       [7, 1],
       [3, 7],
       [5, 4],
       [6, 4],
       [6, 9],
       [1, 4],
       [5, 0],
       [3,

In [84]:
#On remplace maintenant dans la matrice d, certaines cases vides par une case représentant une gazelle dont la valeur est
#égale à 1. On estime qu'il faut remplir la matrice à 48% de gazelles
n = len(positions)
c=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==1 : 
        c=c+1
q=0
while c<0.48*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==1 : 
        q=q+1
    else : 
        d[position[0],position[1]] = 1
        print("En {} on a mis une gazelle".format(position))
        c = c+1
        q=q+1

[0 1]
[8 4]
[4 5]
[7 2]
[9 7]
[1 1]
[1 3]
[8 9]
[8 5]
[7 3]
[0 6]
[8 8]
[9 8]
[4 7]
[6 5]
[0 4]
[3 6]
[3 4]
[5 3]
[7 6]
[1 5]
[2 6]
[6 7]
[7 4]
[8 2]
[3 0]
[6 3]
[0 0]
[2 9]
[3 8]
[3 1]
[7 0]
[9 2]
[2 8]
[2 0]
[9 3]
[5 6]
[0 3]
[9 5]
[0 5]
[6 6]
[1 9]
[5 7]
[4 0]
[2 4]
[9 9]
[2 5]
[4 2]
[6 1]
[3 3]
[9 0]
[9 4]
[5 1]
[4 6]
[5 9]
[8 3]
[5 5]
[0 9]
[3 9]
[7 1]
[3 7]
[5 4]
[6 4]
[6 9]
[1 4]
[5 0]
[3 2]
[0 2]
[9 6]
[7 5]
[9 1]
[0 7]
[7 9]
[4 8]
[4 1]
[2 2]
[1 6]
[1 2]
[4 9]
[6 2]
[1 7]
[2 7]
[4 3]
[8 7]
[2 3]
[8 1]
[7 8]
[0 8]
[5 8]
[6 8]
[6 0]
[1 0]
[2 1]
[5 2]
[1 8]
[4 4]
[7 7]
[3 5]
[8 6]
[8 0]
En [0 1] on a mis une gazelle
En [8 4] on a mis une gazelle
En [4 5] on a mis une gazelle
En [7 2] on a mis une gazelle
En [9 7] on a mis une gazelle
En [1 1] on a mis une gazelle
En [1 3] on a mis une gazelle
En [8 9] on a mis une gazelle
En [8 5] on a mis une gazelle
En [7 3] on a mis une gazelle
En [0 6] on a mis une gazelle
En [8 8] on a mis une gazelle
En [9 8] on a mis une gazelle
En [4 7] o

In [85]:
#On remplace maintenant quelques cases vide par une case représenant les lions. 
#On estime qu'ils sont présents à 4%
n = len(positions)
x=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==2 : 
        x=x+1
q=0
while x<0.04*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==2 : 
        q=q+1
    elif value == 1 :
        q=q+1
    else : 
        d[position[0],position[1]] = 2
        print("En {} on a mis un lion".format(position))
        x = x+1
        q=q+1

[0 1]
[8 4]
[4 5]
[7 2]
[9 7]
[1 1]
[1 3]
[8 9]
[8 5]
[7 3]
[0 6]
[8 8]
[9 8]
[4 7]
[6 5]
[0 4]
[3 6]
[3 4]
[5 3]
[7 6]
[1 5]
[2 6]
[6 7]
[7 4]
[8 2]
[3 0]
[6 3]
[0 0]
[2 9]
[3 8]
[3 1]
[7 0]
[9 2]
[2 8]
[2 0]
[9 3]
[5 6]
[0 3]
[9 5]
[0 5]
[6 6]
[1 9]
[5 7]
[4 0]
[2 4]
[9 9]
[2 5]
[4 2]
[6 1]
[3 3]
[9 0]
[9 4]
[5 1]
[4 6]
[5 9]
[8 3]
[5 5]
[0 9]
[3 9]
[7 1]
[3 7]
[5 4]
[6 4]
[6 9]
[1 4]
[5 0]
[3 2]
[0 2]
[9 6]
[7 5]
[9 1]
[0 7]
[7 9]
[4 8]
[4 1]
[2 2]
[1 6]
[1 2]
[4 9]
[6 2]
[1 7]
[2 7]
[4 3]
[8 7]
[2 3]
[8 1]
[7 8]
[0 8]
[5 8]
[6 8]
[6 0]
[1 0]
[2 1]
[5 2]
[1 8]
[4 4]
[7 7]
[3 5]
[8 6]
[8 0]
En [6 1] on a mis un lion
En [3 3] on a mis un lion
En [9 0] on a mis un lion
En [9 4] on a mis un lion


In [86]:
#On rajoute maintenant les meutes de lionnes éstimées à 8%
n = len(positions)
y=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==3 : 
        y=y+1
q=0
while y<0.08*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value == 3 : 
        q=q+1
    elif value == 1 :
        q=q+1
    elif value == 2 :
        q=q+1
    else : 
        d[position[0],position[1]] = 3
        print("En {} on a mis une lionne".format(position))
        y = y+1
        q=q+1

En [5 1] on a mis une lionne
En [4 6] on a mis une lionne
En [5 9] on a mis une lionne
En [8 3] on a mis une lionne
En [5 5] on a mis une lionne
En [0 9] on a mis une lionne
En [3 9] on a mis une lionne
En [7 1] on a mis une lionne


In [87]:
#On affiche maintenant la matrice d avec toute la population placée aléatoirement. 
d

array([[ 1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  3.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  2.,  1.,  0.,  1.,  0.,  1.,  3.],
       [ 1.,  0.,  1.,  0.,  0.,  1.,  3.,  1.,  0.,  0.],
       [ 0.,  3.,  0.,  1.,  0.,  3.,  1.,  1.,  0.,  3.],
       [ 0.,  2.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  3.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  3.,  1.,  1.,  0.,  0.,  1.,  1.],
       [ 2.,  0.,  1.,  1.,  2.,  1.,  0.,  1.,  1.,  1.]])

In [88]:
d.size

100

In [89]:
len(np.where(d == 1.)[0])

48

In [90]:
len(np.where(d == 2.)[0])

4

In [91]:
len(np.where(d == 3.)[0])

8

In [ ]:
#On s'interrese maintenant aux interractions entre les gazelles et les lions/meutes de lionnes
#Pour l'instant on se met dans le cas ou dès lors qu'il y a rencontre entre gazelle et lion/meute de lionne, 
#la gazelle se fait attraper et elle fait donc place à une nouvelle case vide dont la valeur est 0


In [ ]:
def voisins(x, y, carte):
    """Renvoie les voisins de (x,y) dans carte en faisant attention aux coins/bords"""
    