In [179]:
import matplotlib

In [180]:
import numpy as np

In [181]:
#Dans la zone étudiée, on estime qu'il y a 4 fois plus de gazelles que de lions/lionnes
#Ainsi sur une zone matrice de 25 "cases" on comptera 12 gazelles, 3 lions/lionnes et donc 10 cases vides
#La gazelle prend comme valeur 1
#La meute de lionne prend la valeur 2
#Le lion prend la valeur 3
np.array([[1,0,0,1,1],[0,1,3,0,1],[0,1,0,1,2],[1,0,1,0,1],[0,2,0,1,1]])

array([[1, 0, 0, 1, 1],
       [0, 1, 3, 0, 1],
       [0, 1, 0, 1, 2],
       [1, 0, 1, 0, 1],
       [0, 2, 0, 1, 1]])

In [252]:
a=10
b=10
d = np.zeros((a,b))
d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [253]:
L=[]
for k in range (0,a) : 
    for i in range (0,a) : 
        L.append([k,i])

In [254]:
L

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [0, 8],
 [0, 9],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [1, 5],
 [1, 6],
 [1, 7],
 [1, 8],
 [1, 9],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [2, 5],
 [2, 6],
 [2, 7],
 [2, 8],
 [2, 9],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3],
 [3, 4],
 [3, 5],
 [3, 6],
 [3, 7],
 [3, 8],
 [3, 9],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [4, 8],
 [4, 9],
 [5, 0],
 [5, 1],
 [5, 2],
 [5, 3],
 [5, 4],
 [5, 5],
 [5, 6],
 [5, 7],
 [5, 8],
 [5, 9],
 [6, 0],
 [6, 1],
 [6, 2],
 [6, 3],
 [6, 4],
 [6, 5],
 [6, 6],
 [6, 7],
 [6, 8],
 [6, 9],
 [7, 0],
 [7, 1],
 [7, 2],
 [7, 3],
 [7, 4],
 [7, 5],
 [7, 6],
 [7, 7],
 [7, 8],
 [7, 9],
 [8, 0],
 [8, 1],
 [8, 2],
 [8, 3],
 [8, 4],
 [8, 5],
 [8, 6],
 [8, 7],
 [8, 8],
 [8, 9],
 [9, 0],
 [9, 1],
 [9, 2],
 [9, 3],
 [9, 4],
 [9, 5],
 [9, 6],
 [9, 7],
 [9, 8],
 [9, 9]]

In [255]:
indices = np.random.choice(np.arange(len(L)), a*b, replace=False)

In [256]:
positions = np.array(L)[indices]

In [257]:
positions

array([[0, 6],
       [2, 6],
       [5, 7],
       [9, 9],
       [3, 4],
       [4, 8],
       [0, 2],
       [9, 5],
       [2, 1],
       [2, 0],
       [5, 9],
       [1, 3],
       [4, 4],
       [1, 4],
       [3, 9],
       [9, 6],
       [0, 1],
       [4, 2],
       [3, 7],
       [8, 9],
       [9, 8],
       [3, 8],
       [6, 2],
       [1, 8],
       [3, 0],
       [7, 9],
       [7, 8],
       [7, 1],
       [3, 1],
       [5, 0],
       [3, 6],
       [5, 2],
       [8, 3],
       [7, 0],
       [0, 5],
       [4, 9],
       [7, 3],
       [9, 1],
       [1, 7],
       [9, 2],
       [3, 5],
       [9, 4],
       [4, 0],
       [0, 9],
       [1, 9],
       [5, 8],
       [6, 3],
       [6, 5],
       [8, 4],
       [6, 8],
       [8, 1],
       [3, 3],
       [2, 2],
       [6, 6],
       [5, 4],
       [5, 1],
       [9, 0],
       [1, 1],
       [2, 7],
       [8, 7],
       [0, 4],
       [1, 5],
       [4, 3],
       [0, 8],
       [6, 9],
       [1, 6],
       [1,

In [258]:
def add_gazelle(d, positions):
    n = len(positions)
    c=0
    for k in range (0,n) :
        position = positions[k]
        value = d[position[0],position[1]]
        if value==1 : 
            c=c+1
    q=0
    while c<0.48*n :
        position = positions[q]
        value = d[position[0],position[1]]
        if value==1 : 
            q=q+1
        else : 
            d[position[0],position[1]] = 1
            c = c+1
            q=q+1
        return 
    

In [259]:
n = len(positions)
c=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==1 : 
        c=c+1
q=0
while c<0.48*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==1 : 
        q=q+1
    else : 
        d[position[0],position[1]] = 1
        c = c+1
        q=q+1

In [260]:
d

array([[ 0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.]])

In [261]:
# add_lion(d, positions_bis)

In [262]:
#lions
n = len(positions)
x=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==2 : 
        x=x+1
q=0
while x<0.04*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==2 : 
        q=q+1
    if value == 1 :
        q=q+1
    else : 
        d[position[0],position[1]] = 2
        x = x+1
        q=q+1

In [263]:
d

array([[ 0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  2.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  2.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  2.,  0.,  1.,  2.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.]])

In [264]:
n = len(positions)
y=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==3 : 
        y=y+1
q=0
while y<0.08*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value == 3 : 
        q=q+1
    if value == 1 :
        q=q+1
    if value == 2 :
        q=q+1
    else : 
        d[position[0],position[1]] = 3
        y = y+1
        q=q+1

In [265]:
d

array([[ 0.,  1.,  3.,  0.,  0.,  1.,  3.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,  1.],
       [ 1.,  3.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  2.,  3.,  1.,  1.,  1.,  1.,  3.],
       [ 1.,  0.,  1.,  0.,  3.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  0.,  1.,  0.,  0.,  0.,  0.,  3.,  1.,  3.],
       [ 0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  2.,  0.],
       [ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  2.,  0.,  1.,  2.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.]])