In [1]:
import matplotlib

In [2]:
import numpy as np

In [3]:
#Dans la zone étudiée, on estime qu'il y a 4 fois plus de gazelles que de lions/lionnes
#Ainsi, par exemple, sur une zone matrice de 25 "cases" on comptera 12 gazelles, 3 lions/lionnes et donc 10 cases vides
#La gazelle prend comme valeur 1
#La meute de lionne prend la valeur 2
#Le lion prend la valeur 3
#Une case vide prend la valeur 0

In [5]:
#Création d'une matrice d composée uniquement de 0 représentant une case vide
#matrice composée de a lignes et b colonnes (a et b étant des valeurs que l'on peut modifier directement dans le programme)
a=10
b=10
d = np.zeros((a,b))
d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
#Création d'une liste L avec toutes les positions possibles de la matrice d 
L=[]
for k in range (0,a) : 
    for i in range (0,a) : 
        L.append([k,i])

In [254]:
L

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [0, 8],
 [0, 9],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [1, 5],
 [1, 6],
 [1, 7],
 [1, 8],
 [1, 9],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [2, 5],
 [2, 6],
 [2, 7],
 [2, 8],
 [2, 9],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3],
 [3, 4],
 [3, 5],
 [3, 6],
 [3, 7],
 [3, 8],
 [3, 9],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 4],
 [4, 5],
 [4, 6],
 [4, 7],
 [4, 8],
 [4, 9],
 [5, 0],
 [5, 1],
 [5, 2],
 [5, 3],
 [5, 4],
 [5, 5],
 [5, 6],
 [5, 7],
 [5, 8],
 [5, 9],
 [6, 0],
 [6, 1],
 [6, 2],
 [6, 3],
 [6, 4],
 [6, 5],
 [6, 6],
 [6, 7],
 [6, 8],
 [6, 9],
 [7, 0],
 [7, 1],
 [7, 2],
 [7, 3],
 [7, 4],
 [7, 5],
 [7, 6],
 [7, 7],
 [7, 8],
 [7, 9],
 [8, 0],
 [8, 1],
 [8, 2],
 [8, 3],
 [8, 4],
 [8, 5],
 [8, 6],
 [8, 7],
 [8, 8],
 [8, 9],
 [9, 0],
 [9, 1],
 [9, 2],
 [9, 3],
 [9, 4],
 [9, 5],
 [9, 6],
 [9, 7],
 [9, 8],
 [9, 9]]

In [9]:
indices = np.random.choice(np.arange(len(L)), a*b, replace=False)


In [10]:
#Création d'un tableau "positions" représentant toutes les positions de la matrice "d" dans le désordre 
positions = np.array(L)[indices]

In [11]:
positions

array([[5, 7],
       [5, 2],
       [1, 0],
       [8, 4],
       [2, 2],
       [7, 8],
       [0, 6],
       [2, 4],
       [1, 5],
       [1, 4],
       [6, 8],
       [8, 2],
       [0, 7],
       [6, 6],
       [0, 8],
       [3, 5],
       [7, 4],
       [0, 9],
       [1, 9],
       [4, 3],
       [8, 6],
       [0, 0],
       [4, 1],
       [6, 0],
       [0, 1],
       [1, 3],
       [5, 3],
       [3, 0],
       [2, 3],
       [5, 5],
       [4, 0],
       [7, 3],
       [7, 0],
       [3, 2],
       [4, 4],
       [1, 8],
       [8, 0],
       [4, 7],
       [0, 5],
       [6, 1],
       [2, 7],
       [8, 7],
       [9, 4],
       [6, 9],
       [0, 3],
       [4, 9],
       [5, 4],
       [9, 5],
       [5, 9],
       [3, 8],
       [5, 1],
       [6, 3],
       [4, 6],
       [6, 2],
       [7, 7],
       [1, 6],
       [5, 8],
       [3, 7],
       [2, 0],
       [6, 7],
       [8, 1],
       [3, 3],
       [9, 6],
       [5, 0],
       [4, 8],
       [5, 6],
       [1,

In [17]:
#On remplace maintenant dans la matrice d, certaines cases vides par une case représentant une gazelle dont la valeur est
#égale à 1. On estime qu'il faut remplir la matrice à 48% de gazelles
n = len(positions)
c=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==1 : 
        c=c+1
q=0
while c<0.48*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==1 : 
        q=q+1
    else : 
        d[position[0],position[1]] = 1
        c = c+1
        q=q+1

In [18]:
#On remplace maintenant quelques cases vide par une case représenant les lions. 
#On estime qu'ils sont présents à 4%
n = len(positions)
x=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==2 : 
        x=x+1
q=0
while x<0.04*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==2 : 
        q=q+1
    if value == 1 :
        q=q+1
    else : 
        d[position[0],position[1]] = 2
        x = x+1
        q=q+1

In [19]:
#On rajoute maintenant les meutes de lionnes éstimées à 8%
n = len(positions)
y=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==3 : 
        y=y+1
q=0
while y<0.08*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value == 3 : 
        q=q+1
    if value == 1 :
        q=q+1
    if value == 2 :
        q=q+1
    else : 
        d[position[0],position[1]] = 3
        y = y+1
        q=q+1

In [20]:
#On affiche maintenant la matrice d avec toute la population placée aléatoirement. 
d

array([[ 1.,  1.,  0.,  1.,  0.,  1.,  3.,  3.,  3.,  1.],
       [ 3.,  0.,  0.,  1.,  1.,  3.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  3.,  1.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  2.,  0.],
       [ 1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  2.,  1.,  1.,  1.,  1.,  0.,  3.,  0.,  2.],
       [ 1.,  1.,  0.,  2.,  0.,  0.,  1.,  0.,  3.,  1.],
       [ 1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.]])