In [ ]:
import matplotlib

In [ ]:
import numpy as np

In [ ]:
from random import *

In [ ]:
#Dans la zone étudiée, on estime qu'il y a 4 fois plus de gazelles que de lions/lionnes
#Ainsi, par exemple, sur une zone matrice de 25 "cases" on comptera 12 gazelles, 3 lions/lionnes et donc 10 cases vides
#La gazelle prend comme valeur 1
#La meute de lionne prend la valeur 2
#Le lion prend la valeur 3
#Une case vide prend la valeur 0

In [ ]:
#Création d'une matrice d composée uniquement de 0 représentant une case vide
#matrice composée de a lignes et b colonnes (a et b étant des valeurs que l'on peut modifier directement dans le programme)
a=10
b=10
d = np.zeros((a,b))
d

In [ ]:
#Création d'une liste M avec toutes les positions possibles de la matrice d 
M=[]
for k in range (0,a) : 
    for i in range (0,b) : 
        M.append([k,i])

In [ ]:
M

In [ ]:
indices = np.random.choice(np.arange(len(M)), a*b, replace=False)


In [ ]:
#Création d'un tableau "positions" représentant toutes les positions de la matrice "d" dans le désordre 
positions = np.array(M)[indices]

In [ ]:
positions

In [785]:
#On remplace maintenant dans la matrice d, certaines cases vides par une case représentant une gazelle dont la valeur est
#égale à 1. On estime qu'il faut remplir la matrice à 48% de gazelles
n = len(positions)
c=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==1 : 
        c=c+1
q=0
while c<0.48*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==1 : 
        q=q+1
    else : 
        d[position[0],position[1]] = 1
        print("En {} on a mis une gazelle".format(position))
        c = c+1
        q=q+1

[8 7]
[0 1]
[6 0]
[4 6]
[6 4]
[7 8]
[5 3]
[4 5]
[1 6]
[5 1]
[4 9]
[0 0]
[6 2]
[1 7]
[2 0]
[2 6]
[1 0]
[7 7]
[8 1]
[4 1]
[0 7]
[0 6]
[4 3]
[9 8]
[6 6]
[0 3]
[5 9]
[9 5]
[5 5]
[2 5]
[9 2]
[3 3]
[8 0]
[8 6]
[2 7]
[3 5]
[9 3]
[5 7]
[3 4]
[9 7]
[6 7]
[3 0]
[4 2]
[6 5]
[4 8]
[1 8]
[7 5]
[7 3]
[8 2]
[7 1]
[3 9]
[9 6]
[3 8]
[9 4]
[3 1]
[5 6]
[8 9]
[7 4]
[7 0]
[1 1]
[0 9]
[2 8]
[3 7]
[0 2]
[0 8]
[6 8]
[8 4]
[9 9]
[6 9]
[8 8]
[8 5]
[6 3]
[0 4]
[2 4]
[2 2]
[3 2]
[4 7]
[5 0]
[5 8]
[2 9]
[1 2]
[4 0]
[6 1]
[1 3]
[2 3]
[2 1]
[7 9]
[8 3]
[9 0]
[4 4]
[1 9]
[3 6]
[9 1]
[5 4]
[5 2]
[1 4]
[0 5]
[1 5]
[7 6]
[7 2]
En [0 1] on a mis une gazelle
En [6 0] on a mis une gazelle
En [4 6] on a mis une gazelle
En [7 8] on a mis une gazelle
En [5 3] on a mis une gazelle
En [4 5] on a mis une gazelle
En [5 1] on a mis une gazelle
En [0 0] on a mis une gazelle
En [1 0] on a mis une gazelle
En [7 7] on a mis une gazelle
En [8 1] on a mis une gazelle
En [4 1] on a mis une gazelle
En [4 3] on a mis une gazelle
En [9 8] o

In [786]:
#On remplace maintenant quelques cases vide par une case représenant les lions. 
#On estime qu'ils sont présents à 4%
n = len(positions)
x=0
for k in range (0,n) :
    position = positions[k]
    print(position)
    value = d[position[0],position[1]]
    if value==2 : 
        x=x+1
q=0
while x<0.04*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value==2 : 
        q=q+1
    elif value == 1 :
        q=q+1
    else : 
        d[position[0],position[1]] = 2
        print("En {} on a mis un lion".format(position))
        x = x+1
        q=q+1

[8 7]
[0 1]
[6 0]
[4 6]
[6 4]
[7 8]
[5 3]
[4 5]
[1 6]
[5 1]
[4 9]
[0 0]
[6 2]
[1 7]
[2 0]
[2 6]
[1 0]
[7 7]
[8 1]
[4 1]
[0 7]
[0 6]
[4 3]
[9 8]
[6 6]
[0 3]
[5 9]
[9 5]
[5 5]
[2 5]
[9 2]
[3 3]
[8 0]
[8 6]
[2 7]
[3 5]
[9 3]
[5 7]
[3 4]
[9 7]
[6 7]
[3 0]
[4 2]
[6 5]
[4 8]
[1 8]
[7 5]
[7 3]
[8 2]
[7 1]
[3 9]
[9 6]
[3 8]
[9 4]
[3 1]
[5 6]
[8 9]
[7 4]
[7 0]
[1 1]
[0 9]
[2 8]
[3 7]
[0 2]
[0 8]
[6 8]
[8 4]
[9 9]
[6 9]
[8 8]
[8 5]
[6 3]
[0 4]
[2 4]
[2 2]
[3 2]
[4 7]
[5 0]
[5 8]
[2 9]
[1 2]
[4 0]
[6 1]
[1 3]
[2 3]
[2 1]
[7 9]
[8 3]
[9 0]
[4 4]
[1 9]
[3 6]
[9 1]
[5 4]
[5 2]
[1 4]
[0 5]
[1 5]
[7 6]
[7 2]


In [787]:
#On rajoute maintenant les meutes de lionnes éstimées à 8%
n = len(positions)
y=0
for k in range (0,n) :
    position = positions[k]
    value = d[position[0],position[1]]
    if value==3 : 
        y=y+1
q=0
while y<0.08*n :
    position = positions[q]
    value = d[position[0],position[1]]
    if value == 3 : 
        q=q+1
    elif value == 1 :
        q=q+1
    elif value == 2 :
        q=q+1
    else : 
        d[position[0],position[1]] = 3
        print("En {} on a mis une lionne".format(position))
        y = y+1
        q=q+1

En [3 8] on a mis une lionne
En [9 4] on a mis une lionne
En [3 1] on a mis une lionne
En [5 6] on a mis une lionne
En [8 9] on a mis une lionne
En [7 4] on a mis une lionne
En [7 0] on a mis une lionne
En [1 1] on a mis une lionne


In [788]:
#On affiche maintenant la matrice d avec toute la population placée aléatoirement. 
d

array([[ 1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 1.,  3.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  3.,  0.,  1.,  1.,  1.,  0.,  0.,  3.,  2.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  3.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 3.,  2.,  0.,  1.,  3.,  1.,  0.,  1.,  1.,  0.],
       [ 1.,  1.,  2.,  0.,  0.,  0.,  1.,  1.,  0.,  3.],
       [ 0.,  0.,  1.,  1.,  3.,  1.,  2.,  1.,  1.,  0.]])

In [789]:
d.size

100

In [790]:
len(np.where(d == 1.)[0])

48

In [791]:
len(np.where(d == 2.)[0])

4

In [792]:
len(np.where(d == 3.)[0])

8

In [793]:
#On s'interesse aux voisins de chaque case
def voisins(x,y) : 
    """Renvoie aléatoirement un des voisins de (x,y) dans la matrice d en faisant attention aux coins/bords"""
    L = []

    #coin supérieur gauche
    if x == 0 and y == 0 : 
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
    
    #coin supérieur droit
    elif x == 0 and y == (b-1) : 
        L.append(d[(x+1),y])
        L.append(d[x,(y-1)])
    
    #coin inférieur gauche
    elif x == (a-1) and y == 0 : 
        L.append(d[x,(y+1)])
        L.append(d[(x-1),y])
    
    #coin inférieur droit
    elif x == (a-1) and y == (b-1) : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
    
    #ligne du haut
    elif x == 0 and y != 0:
        L.append(d[(x,(y-1))])
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
        
    #ligne de gauche
    elif x !=0 and y == 0 : 
        L.append(d[(x-1),y])
        L.append(d[(x+1),y])
        L.append(d[x,(y+1)])
        
    #ligne du bas
    elif x == (a-1) and y != 0 : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
        L.append(d[x,(y+1)])
    
    #ligne de droite
    elif x != 0 and y == (b-1) : 
        L.append(d[(x-1),y])
        L.append(d[x,(y-1)])
        L.append(d[(x+1),y])

    #cas général
    else :
        L.append(d[x,(y-1)])
        L.append(d[(x-1),y])
        L.append(d[x,(y+1)])
        L.append(d[(x+1),y])

    g = choice(L)
   
    return g
    

In [794]:
d

array([[ 1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 1.,  3.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  3.,  0.,  1.,  1.,  1.,  0.,  0.,  3.,  2.],
       [ 0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  3.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 3.,  2.,  0.,  1.,  3.,  1.,  0.,  1.,  1.,  0.],
       [ 1.,  1.,  2.,  0.,  0.,  0.,  1.,  1.,  0.,  3.],
       [ 0.,  0.,  1.,  1.,  3.,  1.,  2.,  1.,  1.,  0.]])

In [795]:
#premier passage des lions/meutes de lionnes sur les gazelles
for k in range (0,a) : 
    for i in range (0,b) : 
        if d[k,i] == 1. and voisins(k,i) == 2. :
            d[k,i] = 2. 
        if d[k,i] == 1. and voisins(k,i) == 3. : 
            d[k,i] = 3. 
          

In [796]:
len(np.where(d == 1.)[0])

45

In [797]:
c = len(np.where(d == 3.)[0])
c

11

In [798]:
n = d.size
n

100

In [ ]:
#réguler le nombre de meutes de lionnes présents dans la matrice afin de stabiliser son nombre à 8%
while c > 0.08*n : 
    for k in range (0,a) :
        for i in range (0,b) :
            if d[k,i] == 3 : 
                d[k,i] = 0
            else :
                d[k,i] = 3


In [ ]:
len(np.where(d == 3.)[0])

In [758]:
d

array([[ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  2.,  2.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.],
       [ 1.,  2.,  2.,  0.,  0.,  0.,  2.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.,  2.,  0.]])

In [726]:
a

10

In [ ]:
len(np.where(d == 3.)[0])

In [ ]:
#On s'interrese maintenant aux interractions entre les gazelles et les lions/meutes de lionnes
#Pour l'instant on se met dans le cas ou dès lors qu'il y a rencontre entre gazelle et lion/meute de lionne, 
#la gazelle se fait attraper et elle fait donc place à une nouvelle case vide dont la valeur est 0